### Site Settings ###
title               : Robert Marzec
description         : a software developer's website
baseurl             : ""                               # Change to empty quotes if you are hosting your site at <your-username>.github.io directly


### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


### Navbar Settings ###
nav_include:
  - pages/**

nav_exclude:                                            # The following paths are excluded from navbar
  - pages/privacy
  - pages/404
  - pages/igda1
  - pages/igda2


### Author Info ###
author:
  name              : Robert Marzec
  image             : /assets/images/about-photo.jpg
# behance           : your_username
# dribbble          : your_username
  email             : robertmarzecj@gmail.com
# facebook          : your_username
  github            : rjmarzec
# gitlab            : your_username
# instagram         : your_username
  linkedin          : rjmarzec
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : rjmarzec_
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections_dir: collections
collections:
  devtober-2021:
    output: true
    permalink: /:collection/:title
# projects:
#   output: true
#   permalink: /projects/:name


### Disqus ###
disqus:
  shortname: rjmarzec                                   # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                         # Set true to enable analytics
  google:
    tracking_id: UA-187912924-1


### Defaults for collections ###
defaults:
  - scope:
      path: "projects/*/about.md"
      type: "pages"
    values:
      layout: "page"
      read_time: false
      comments: false
      permalink: "/:path"
  - scope:
      path: "projects/*/play.md"
      type: "pages"
    values:
      layout: "page"
      read_time: false
      comments: false
      permalink: "/:path/play"
  - scope:
      path: "projects/*/postmortem.md"
      type: "pages"
    values:
      layout: "post"
      read_time: true
      comments: true
      permalink: "/:path/postmortem"
  - scope:
      path: "projects/~template/"
      type: "pages"
    values:
      published: false


### Exclude from processing ###
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - '*.log'
  - '*.css'
  - 'projects/*/*/index.html'
  - post/projects

### Enabling incremental builds to improve build times locally
incremental: true
